### ISSUE TITLE
Icon with multiple <g> elements

### ISSUE THREAD

**Issue by cyril94440** [alexk111/SVG-Morpheus#10]
Hi, 

thanks for your library that's awesome.

However, I encounter a problem with svg generated with illustrator, they contain multiple <g> tag.
How should I proceed ?

Thanking you in advance.

**Comment by alexk111** [comment]
@cyril94440 [Combine shapes](https://helpx.adobe.com/illustrator/using/combining-objects.html) before exporting to svg, to get (ideally) one ```<path>``` tag per icon.
