### ISSUE TITLE
Getting a console error in Safari

### ISSUE THREAD

**Issue by lakeebs** [alexk111/SVG-Morpheus#11]
[Live site](http://staging.keebs.com/) (click on 'Get in Touch' at the top right)

The icon is supposed to morph but it throws out a console error: 
`TypeError: 'undefined' is not a function (evaluating 'u(this._rafid)')`

Works okay in Chrome, FF, and IE, though. Btw, I'm on Windows.

**Comment by alexk111** [comment]
@lakeebs Does that occur on Safari for Windows? That's a [dead browser](http://appleinsider.com/articles/12/07/25/apple_kills_windows_pc_support_in_safari_60). Please re-open the issue, if that appeared on iOS or OSX.
