### ISSUE TITLE
NPM distribution

### ISSUE THREAD

**Issue by Shearerbeard** [alexk111/SVG-Morpheus#15]
Great library! Is there any chance we could publish this to NPM? We build off of webpack and mostly store our dependencies in npm, this is currently our only library in bower and it would be awesome to have one less config file. Thanks!

**Comment by hugihlynsson** [comment]
+1

**Comment by zack9433** [comment]
:+1:

**Comment by JobaDiniz** [comment]
+1

**Comment by timroes** [comment]
+1

**Comment by apertureless** [comment]
+1

**Comment by eymengunay** [comment]
@timroes It may not be the best solution but for now you can use:
```
npm install alexk111/SVG-Morpheus
```
see [npm docs](https://docs.npmjs.com/cli/install)

**Comment by thebergamo** [comment]
why not publish on npm?

**Comment by parliament718** [comment]
+1

**Comment by alexk111** [comment]
Can't publish the library on npm, as the original name was taken by a squatter (nothing is hosted with that package name). Sent a message to npm support. Will publish it as soon as the issue will be resolved on the npm side.

**Comment by apertureless** [comment]
why not simply switch the package name? morpheus-svg .

**Comment by alexk111** [comment]
Done! Published on NPM as svg-morpheus
