### ISSUE TITLE
I can use this on own project?

### ISSUE THREAD

**Issue by dalisoft** [alexk111/SVG-Morpheus#16]
Hi!
I can use this project to my own project?
It's free to use on other projects?

**Comment by taxilian** [comment]
Read the LICENSE in the root of the project; it's licensed MIT, which basically means use it however you want but make sure the copyright and license remain intact.

see https://tldrlegal.com/license/mit-license

**Comment by alexk111** [comment]
@taxilian Thank you for the reply!
