### ISSUE TITLE
SVG Morpheus has a issue with morph

### ISSUE THREAD

**Issue by dalisoft** [alexk111/SVG-Morpheus#17]
http://codepen.io/dalisoft/pen/qOQrwz

When countdown for 5,4,3,2,1,0 morphing not smooth

UPDATE: Discussion here, http://greensock.com/forums/topic/13157-svg-morph-difference/

**Comment by alexk111** [comment]
@dalisoft Thank you for the links! Will research that.

**Comment by dalisoft** [comment]
Hi @alexk111.
Thanks for amazing morpheus code, i'm used it's on my code and works like charm, i did something wrong ( exactly something wrong with paths ). I credited you in my credits part. Thanks.
https://github.com/dalisoft/Unim.js
http://codepen.io/dalisoft/full/XdoVaK/
