### ISSUE TITLE
How can I get the svg paths in the morpheus-transform process?

### ISSUE THREAD

**Issue by BaoyangBob** [alexk111/SVG-Morpheus#18]
I'm an Android developer, not a web developer,and I know little about javascript.I saw the delight detail in google's Material Design guidelines,so I hope to make some similar buttons.What I want is to capture a set of svg paths in the process.Should I use the follow code in function  "SVGMorpheus.prototype._updateAnimationProgress" (Line 362)in "\source\js\svg-morpheus.js"?
```javascript
console.log(this._curIconItems[i].path);
```
3Q,my email:MichaelBockson@gmail.com

**Comment by alexk111** [comment]
@BaoyangBob Yeah, you may put the console line before [that one](https://github.com/alexk111/SVG-Morpheus/blob/v0.1.8/source/js/svg-morpheus.js#L383) to get all the paths generated during the morph process.
