### ISSUE TITLE
Webpack support

### ISSUE THREAD

**Issue by ahamo** [alexk111/SVG-Morpheus#24]
Firstly, great library.

Had a little issue using it with Webpack.

- Installed using Bower
- import SVGMorpheus from 'svg-morpheus';

However empty object was being returned. Ended up changing the default src file to the unminified version and exposing by - module.exports = SVGMorpheus

Is there a better way to import this file for use with Webpack?

Cheers

**Comment by alexk111** [comment]
@ahamo That should work ok now. Please get the ```version 0.3.1``` and try again.

**Comment by ahamo** [comment]
Thanks Alex, you're a champ @alexk111

**Comment by cho-is** [comment]
would you please upgrade `npm` module?
