### ISSUE TITLE
Need sample of your script

### ISSUE THREAD

**Issue by artrainbow** [alexk111/SVG-Morpheus#5]
Dear, Alexk111. Help me pls.
I need morphing icon1 to icon2 by SVG-Morpheus. Whats wrong in my code and where i should to write options of morphing?

https://gist.github.com/anonymous/d29b9c16842dd7a43387

**Comment by alexk111** [comment]
@artrainbow you need to add ```id="myIconSet"``` to the ```<svg>```, init ```var options={}``` and ```var callback=function() { }``` before calling the ```var myIcons = new SVGMorpheus('#myIconsSet' , options, callback);```
