### ISSUE TITLE
Whether it can support the <symbol> element, and not just the <g> element

### ISSUE THREAD

**Issue by zhangxinxu** [alexk111/SVG-Morpheus#6]
Whether it can support the <symbol> element, and not just the <g> element? As you known, SVG-sprites that use <symbol> element are becoming more common.

**Comment by romanran** [comment]
I have the same issue

**Comment by alexk111** [comment]
@zhangxinxu @romanran Please provide more details on your use cases. ```<symbol>``` only describes a svg object model, and then you render it with ```<use>```, which means that if SVG Morpheus would morph the symbol, all the ```<use>``` linked with that symbol will morph with it. I'm not sure that this would be a nice idea. What do you think?

**Comment by dalisoft** [comment]
I sure, `<symbol>` not necessary for morphing as many web developers morphing `SVG` and most `path` tag. Thanks
